name: Validate JSON Files

on:
  pull_request:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: Find and validate JSON files
      run: |
        for file in $(find . -name "*.json"); do
          echo "Validating $file"
          cat "$file" | jq empty
        done
